### ISSUE TITLE
Fix Discourse SMTP settings

### ISSUE THREAD

**Issue by JMLX42** [democratech/2022#9]

**Comment by JMLX42** [comment]
```
/opt/bitnami/ruby/lib/ruby/2.6.0/net/smtp.rb:539:in `initialize'
/opt/bitnami/ruby/lib/ruby/2.6.0/net/smtp.rb:539:in `open'
/opt/bitnami/ruby/lib/ruby/2.6.0/net/smtp.rb:539:in `tcp_socket'
/opt/bitnami/ruby/lib/ruby/2.6.0/net/smtp.rb:549:in `block in do_start'
/opt/bitnami/ruby/lib/ruby/2.6.0/timeout.rb:103:in `timeout'
/opt/bitnami/ruby/lib/ruby/2.6.0/net/smtp.rb:548:in `do_start'
/opt/bitnami/ruby/lib/ruby/2.6.0/net/smtp.rb:518:in `start'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:109:in `start_smtp_session'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/network/delivery_methods/smtp.rb:100:in `deliver!'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:2159:in `do_delivery'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `block in deliver'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/actionmailer-6.0.3.3/lib/action_mailer/base.rb:589:in `block in deliver_mail'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `block in instrument'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/activesupport-6.0.3.3/lib/active_support/notifications.rb:180:in `instrument'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/actionmailer-6.0.3.3/lib/action_mailer/base.rb:587:in `deliver_mail'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mail-2.7.1/lib/mail/message.rb:260:in `deliver'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/actionmailer-6.0.3.3/lib/action_mailer/message_delivery.rb:115:in `block in deliver_now'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/actionmailer-6.0.3.3/lib/action_mailer/rescuable.rb:17:in `handle_exceptions'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/actionmailer-6.0.3.3/lib/action_mailer/message_delivery.rb:114:in `deliver_now'
/opt/bitnami/discourse-sidekiq/lib/email/sender.rb:234:in `send'
/opt/bitnami/discourse-sidekiq/app/jobs/scheduled/version_check.rb:25:in `execute'
/opt/bitnami/discourse-sidekiq/app/jobs/base.rb:232:in `block (2 levels) in perform'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/rails_multisite-2.5.0/lib/rails_multisite/connection_management.rb:76:in `with_connection'
/opt/bitnami/discourse-sidekiq/app/jobs/base.rb:221:in `block in perform'
/opt/bitnami/discourse-sidekiq/app/jobs/base.rb:217:in `each'
/opt/bitnami/discourse-sidekiq/app/jobs/base.rb:217:in `perform'
/opt/bitnami/discourse-sidekiq/app/jobs/base.rb:279:in `perform'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mini_scheduler-0.12.3/lib/mini_scheduler/manager.rb:93:in `process_queue'
/opt/bitnami/discourse-sidekiq/vendor/bundle/ruby/2.6.0/gems/mini_scheduler-0.12.3/lib/mini_scheduler/manager.rb:37:in `block (2 levels) in initialize'
```

**Comment by JMLX42** [comment]
https://www.scaleway.com/en/faq/why-can-i-not-send-any-email/

**Comment by JMLX42** [comment]
I have submitted my Scaleway account through KYC to have access to the "build level" and enable SMTP.

**Comment by JMLX42** [comment]
After the Scaleway KYC succeeded, I was able to enable SMTP in the Security Groups and the Discourse forum email test is now worling as expected => closing.
